# Generated by Django 3.0.3 on 2020-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
