# Generated by Django 3.0.3 on 2020-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_doc_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
