# Generated by Django 3.0.3 on 2020-11-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20201129_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
