# Generated by Django 3.0.3 on 2020-11-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
