# Generated by Django 3.0.3 on 2020-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
                ('weights_url', models.CharField(default='', max_length=255)),
                ('user', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
