# Generated by Django 3.0.3 on 2020-12-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0002_auto_20201201_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='torchmodel',
            name='problem_type',
            field=models.CharField(choices=[('classification', (('resnet18', 'resnet18'), ('resnet34', 'resnet34'))), ('segmentation', (('unet', 'unet'),))], default='resnet18', max_length=8),
        ),
    ]
