# Generated by Django 3.0.3 on 2020-12-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0003_auto_20201201_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchmodel',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
