# Generated by Django 3.0.3 on 2020-12-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0004_torchmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torchmodel',
            name='user',
        ),
    ]
