# Generated by Django 3.0.3 on 2020-12-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0005_remove_torchmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torchmodel',
            name='weights_url',
        ),
    ]
