# Generated by Django 3.0.3 on 2020-12-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0006_remove_torchmodel_weights_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchmodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
