# Generated by Django 3.0.3 on 2020-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0007_torchmodel_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchmodel',
            name='encoding_dict',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='torchmodel',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
