# Generated by Django 3.1.4 on 2020-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0008_auto_20201205_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torchmodel',
            name='api_endpoint',
            field=models.CharField(default='', max_length=255),
        ),
    ]
