# Generated by Django 3.1.4 on 2020-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0009_auto_20201206_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchmodel',
            name='endpoint',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='torchmodel',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
