# Generated by Django 3.1.4 on 2020-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0010_auto_20201208_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torchmodel',
            name='port',
            field=models.CharField(default='', max_length=4),
        ),
    ]
