# Generated by Django 3.1.4 on 2020-12-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0011_auto_20201208_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torchmodel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='torchmodel',
            name='api_endpoint',
        ),
    ]
