# Generated by Django 3.1.4 on 2020-12-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch_model_module', '0012_auto_20201208_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torchmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
